"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "#0077c2"
  foreground = "#ffffff"
  leading_diamond = "╭─"
  style = "diamond"
  template = " {{ .Path }} "
  type = "path"

  [[blocks.segments]]
  background = "#21c7c7"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#21c7c7{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
  "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
  "{{ if gt .Behind 0 }}#C792EA{{ end }}"
]
  foreground = "#ffffff"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    fetch_status = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "#303030"
  foreground = "#3C873A"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
  trailing_diamond = " "
  type = "node"

    [blocks.segments.properties]
    fetch_package_manager = true
    npm_icon = " <#cc3a3a></> "
    yarn_icon = " <#348cba></>"

  [[blocks.segments]]
  background = "#306998"
  foreground = "#FFE873"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
  trailing_diamond = " "
  type = "python"

  [[blocks.segments]]
  background = "#ffffff"
  foreground = "#06aad5"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
  trailing_diamond = " "
  type = "go"

  [[blocks.segments]]
  background = "#f3f0ec"
  foreground = "#925837"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
  trailing_diamond = " "
  type = "rust"

  [[blocks.segments]]
  background = "#565656"
  foreground = "#faa029"
  leading_diamond = ""
  style = "diamond"
  template = " {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
  trailing_diamond = " "
  type = "aws"

  [[blocks.segments]]
  background = "#316ce4"
  foreground = "#ffffff"
  leading_diamond = ""
  style = "diamond"
  template = " ☸️:{{.Context}}{{if .Namespace}}/{{.Namespace}}{{end}} "
  type = "kubectl"

  [[blocks.segments]]
  background = "#f36943"
  background_templates = [
  "{{if eq \"Charging\" .State.String}}#b8e994{{end}}",
  "{{if eq \"Discharging\" .State.String}}#fff34e{{end}}",
  "{{if eq \"Full\" .State.String}}#33DD2D{{end}}"
]
  foreground = "#262626"
  invert_powerline = true
  powerline_symbol = ""
  style = "powerline"
  template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} "
  type = "battery"

    [blocks.segments.properties]
    charged_icon = " "
    charging_icon = " "
    discharging_icon = " "

  [[blocks.segments]]
  background = "#83769c"
  foreground = "#ffffff"
  invert_powerline = true
  style = "diamond"
  trailing_diamond = ""
  template = " {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    style = "roundrock"
    threshold = 0

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#21c7c7"
  style = "plain"
  template = "╰─"
  type = "text"

  [[blocks.segments]]
  foreground = "#e0f8ff"
  foreground_templates = [ "{{ if gt .Code 0 }}#ef5350{{ end }}" ]
  style = "plain"
  template = " "
  type = "status"

    [blocks.segments.properties]
    always_enabled = true
