alias k=kubectl
alias kcx=kubectx
alias kns=kubens
alias ls='ls --color'
alias mkd="mkdir -pv"
alias reload="exec zsh"
alias restow="stow -R -d ${HOME}/Projects/personal/dotfiles -t ${HOME} dotfiles"
alias tf=terraform
alias vim="nvim"
alias watch="watch -n 1"
alias zshconfig="nvim ${HOME}/.zshrc"
alias zbench='for i in {1..10}; do /usr/bin/time zsh -lic exit; done'
alias pc="podman-compose"