#!/bin/zsh

[[ ! -d ${SECRETS_HOME:-$HOME/.local/secrets} ]] && mkdir -p ${SECRETS_HOME:-$HOME/.local/secrets}

for _secret in ${SECRETS_HOME:-$HOME/.local/secrets}/*; do
  # Ignore tilde files.
  [[ $_secret:t != '~'* ]] && source "$_secret"
done
unset _secret
