#! /bin/zsh

[ ! -d "${HOME}/.local/completions" ] && mkdir -p ${HOME}/.local/completions

fpath=(${HOME}/.local/completions $fpath)

source /usr/share/google-cloud-sdk/completion.zsh.inc
source ${HOME}/.local/share/asdf/asdf.sh